name: CD Pipeline - QA

on:
  workflow_run:
    workflows: ["CI Pipeline - Staging/QA"]
    types:
      - completed
  workflow_dispatch:   # optional manual trigger

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secret
        run: |
          if [ -z "${{ secrets.RENDER_CALLBACK_URL_QA }}" ]; then
            echo "❌ Secret EMPTY"
          else
            echo "✅ Secret FOUND"
          fi

      - name: Deploy to Render QA
        run: |
          curl -X POST "${{ secrets.RENDER_CALLBACK_URL_QA }}"