name: CD Pipeline - QA

on:
  workflow_run:
    workflows: ["CI Pipeline - Staging/QA"]  # must match CI workflow name
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - release/**
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render QA
        run: |
          if [ -z "${{ secrets.RENDER_CALLBACK_URL_QA }}" ]; then
            echo "::error::Secret RENDER_CALLBACK_URL_QA is empty or missing!"
            exit 1
          fi

          echo "Triggering Render deploy for QA..."
          curl -X POST -f "${{ secrets.RENDER_CALLBACK_URL_QA }}"